name: PlayerListPlugin
version: 1.2
main: com.gmail.leeyi45.PlayerListPlugin.pluginMain.PlayerListPlugin
commands:
  playerlist:
    description: Command to manage the playerlist plugin
    usage: /playerlist <discord|telegram|update>
    permission: playerlist