name: PlayerListPlugin
version: 1.1
main: com.gmail.leeyi45.PlayerListPlugin.PluginMain.PlayerListPlugin
commands:
  playerlist:
    description: Command to manage the playerlist plugin
    usage: /playerlist {discord|telegram|update}
    permission: com.gmail.leeyi45.playerlist